from fvcore.common.config import CfgNode

CONFIGS = CfgNode(new_allowed=True)
CONFIGS.INPUT_SIZE = (640, 640) # IMAGE SIZE FOR TRAIN, TEST
CONFIGS.IS_RECT = True
CONFIGS.IS_MOSAIC = False
CONFIGS.BATCH_SIZE = 32
CONFIGS.DEVICE = 'cuda'
CONFIGS.apex = False

CONFIGS.TRAINING = CfgNode(new_allowed=True)
CONFIGS.TRAINING.LOGDIR = './logdirs/'
CONFIGS.TRAINING.WEIGHTS = './weights/'
CONFIGS.TRAINING.CHECKPOINT_MODE = 'RESUME'  # ['pretrained', 'resume', 'start']
CONFIGS.TRAINING.CHECKPOINT_FILE = './pretrained/mobilenetv2_pretrained.pkl'
CONFIGS.TRAINING.W_MKF = 1.
CONFIGS.TRAINING.W_VKF = 1.
CONFIGS.TRAINING.W_VFM = 1.
CONFIGS.TRAINING.W_M_OFF = 0.5
CONFIGS.TRAINING.W_V_OFF = 0.5

CONFIGS.DATASET = CfgNode(new_allowed=True)
CONFIGS.DATASET.PATH = './datasets/data/kitti'
CONFIGS.DATASET.OBJs = ['Car', 'Pedestrian', 'Cyclist']
CONFIGS.DATASET.RELATE_OBJs = [['Van', 'Truck'], ['Person_sitting'], ['Person_sitting']]
CONFIGS.DATASET.MEAN = [0.485, 0.456, 0.406]
CONFIGS.DATASET.STD = [0.229, 0.224, 0.225]
CONFIGS.DATASET.BBOX_AREA_MAX = 0.2598311523503046
CONFIGS.DATASET.BBOX_AREA_MIN = 0.0002022788461538487
CONFIGS.DATASET.GAUSSIAN_SIGMA_MAX = 19
CONFIGS.DATASET.GAUSSIAN_SIGMA_MIN = 3
CONFIGS.DATASET.VERTEX_OFFSET_INFER = [0.75, 0.57]
CONFIGS.DATASET.GAUSSIAN_GEN_TYPE = 'dynamic_radius'  # 'dynamic_radius', 'dynamic_sigma'
CONFIGS.DATASET.aug_hsv_h = 0.014  # image HSV-Hue augmentation (fraction)
CONFIGS.DATASET.aug_hsv_s = 0.68  # image HSV-Saturation augmentation (fraction)
CONFIGS.DATASET.aug_hsv_v = 0.36  # image HSV-Value augmentation (fraction)
CONFIGS.DATASET.aug_degrees = 0.0  # image rotation (+/- deg)
CONFIGS.DATASET.aug_translate = 0.0  # image translation (+/- fraction)
CONFIGS.DATASET.aug_scale = 0.5  # image scale (+/- gain)
CONFIGS.DATASET.aug_shear = 0.0  # image shear (+/- deg)

# Solver
# ---------------------------------------------------------------------------- #
CONFIGS.SOLVER = CfgNode(new_allowed=True)

CONFIGS.SOLVER.OPTIM_TYPE = "adam"

CONFIGS.SOLVER.LR_SCHEDULER_NAME = "WarmupMultiStepLR"

CONFIGS.SOLVER.MAX_EPOCH = 1000

CONFIGS.SOLVER.BASE_LR = 0.01

CONFIGS.SOLVER.MOMENTUM = 0.937

CONFIGS.SOLVER.WEIGHT_DECAY = 0.0005
# The weight decay that's applied to parameters of normalization layers
# (typically the affine transformation)
CONFIGS.SOLVER.WEIGHT_DECAY_NORM = 0.0

CONFIGS.SOLVER.GAMMA = 0.1
# The iteration number to decrease learning rate by GAMMA.
CONFIGS.SOLVER.STEPS = (20000, 50000)

CONFIGS.SOLVER.WARMUP_FACTOR = 1.0 / 1000
CONFIGS.SOLVER.WARMUP_ITERS = 1000
CONFIGS.SOLVER.WARMUP_METHOD = "linear"
CONFIGS.SOLVER.EXCLUDE_SCOPE = ()
CONFIGS.SOLVER.INCLUDE_SCOPE = ()
CONFIGS.SOLVER.LOAD_SOLVER = True

CONFIGS.SOLVER.BIAS_LR_FACTOR = 1.0
CONFIGS.SOLVER.WEIGHT_DECAY_BIAS = CONFIGS.SOLVER.WEIGHT_DECAY

CONFIGS.MODEL = CfgNode(new_allowed=True)
CONFIGS.MODEL.BACKBONE = 'DLA-34'
CONFIGS.MODEL.DOWN_SAMPLE = 4.
CONFIGS.MODEL.OUT_CHANNELS = 256
CONFIGS.MODEL.KFNs = ['level2', 'level3', 'level4', 'level5']
CONFIGS.MODEL.FOCAL_LOSS_ALPHA = 2.
CONFIGS.MODEL.FOCAL_LOSS_BEDA = 4.
CONFIGS.MODEL.SMOOTH_L1_LOSS_BETA = 0.1
CONFIGS.MODEL.HEADER_NUM_CONV = 2

CONFIGS.DETECTOR = CfgNode(new_allowed=True)
CONFIGS.DETECTOR.CHECKPOINT = './weights/DLA-34/model_0000004.pt'
CONFIGS.DETECTOR.SCORE_THRESH = 0.5
CONFIGS.DETECTOR.TOPK_CANDIDATES = 30
CONFIGS.DETECTOR.NMS_THRESH_TEST = 0.5
CONFIGS.DETECTOR.DEPTH_REF = (27.9123, 17.4489)
# h, w, l
CONFIGS.DETECTOR.DIM_REF = [[1.52607842, 1.62858147, 3.88396124],[1.76067766, 0.6602296 , 0.84220464],[1.73712792, 0.59677122, 1.76338868]]




